### PR TITLE
Apple clone fine pull request

### PR DESCRIPTION
**Pull request by kirokoNjenga**
*What does this PR do*
-implementing apple clone as per the requirement 
-test the HTML with the validator
-implementing stylelint

### CODE REVIEW

**Comment by shshamim63** [comment]
## Status :ballot_box_with_check:  [ !! Required Changes !! ] :ballot_box_with_check:  : 
___
Hi @Samkiroko  :wave:,
Project contains a readme with a screenshot of the page. Contains an instruction on how to play with this project. Uses Semantic HTML tags, no use of !important, no inline styling, images are wrapped inside links. In one word Awesome job :clap:. But just got an issue with the linter config. It seems that linter is not functional. And that is blocking me to approve this  project.
___
#### Please follow the instruction below to complete the project.
___
### :spades: [Mandatory Changes] :spades: 
--- 
1. The linter is not functional. On this pull request if you click on check, you will see a portion yelling `waiting for checks information`. Which was suppose to render as `no lint error found`. Can you go through this [link](https://github.com/microverseinc/linters-config/tree/master/css) again. Specially with no.1 and 2.
Now what I can see :point_down: 
image

___
### :clubs: [Optional Changes] :clubs: 
---
1. There are some repetition of `position: relative;`, Maybe you can create a class for that and you ca n use it whenever you want to. Remember DRY(Don't Repeat Yourself) concept.
___
 ### Please fix the above mentioned issue and send for another review request.
___
## :herb: Happy Coding :herb: 
### __Shakhawat Hossain__
[Linkedin](https://www.linkedin.com/in/shakhawathossainshamim/) | [Slack](Shakhawat Hossain)

**Comment by kirokoNjenga** [comment]
> ## Status  [ !! Required Changes !! ]  :
> Hi @Samkiroko ,
> Project contains a readme with a screenshot of the page. Contains an instruction on how to play with this project. Uses Semantic HTML tags, no use of !important, no inline styling, images are wrapped inside links. In one word Awesome job . But just got an issue with the linter config. It seems that linter is not functional. And that is blocking me to approve this project.
> 
> #### Please follow the instruction below to complete the project.
> ###  [Mandatory Changes] 
> 1. The linter is not functional. On this pull request if you click on check, you will see a portion yelling `waiting for checks information`. Which was suppose to render as `no lint error found`. Can you go through this [link](https://github.com/microverseinc/linters-config/tree/master/css) again. Specially with no.1 and 2.
>    Now what I can see point_down
>    image
> 
> ###  [Optional Changes] 
> 1. There are some repetition of `position: relative;`, Maybe you can create a class for that and you ca n use it whenever you want to. Remember DRY(Don't Repeat Yourself) concept.
> 
> ### Please fix the above mentioned issue and send for another review request.
> ##  Happy Coding 
> ### **Shakhawat Hossain**
> [Linkedin](https://www.linkedin.com/in/shakhawathossainshamim/) | [Slack](Shakhawat Hossain)

i have no stickler errors
image
- also, no git merge no errors please check again
image

**Review by pelzolga123 — APPROVED** [review]
Approved!

**Comment by pelzolga123** [comment]
## Great  work, congratulation :+1: Project Approved.
You did all changes required previously. Go ahead and merge to master.
_Goodluck in your next project_ *Happy coding*

**Pull request merged**
